token: "rL5vlBP6B18yXk6y"    # lichess OAuth2 Token
url: "https://mskchess.ru/"  # lichess base URL

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "sf"        # binary name of the engine to use
  fairyname: "fsf"
  lcname: "lsf"

abort_time: 20               # time to abort a game in seconds when there is no activity
rate_limiting_delay: 0       # time (in ms) to delay after sending a move to prevent "Too Many Requests" errors

challenge:                   # incoming challenges
  accept_bot: true          # accepts challenges coming from other bots
  max_increment: 180         # maximum amount of increment to accaept a challenge. the max is 180. set to 0 for no increment
  min_increment: 0           # minimum amount of increment to accept a challenge
  uci_options:               # arbitrary UCI options passed to the engine
    Move Overhead: 100       # increase if your bot flags games too often
    Threads: 2               # max CPU threads the engine can use
    Hash: 256                # max memory (in megabytes) the engine can allocate
  fake_think_time: false       # artificially slow down the bot to pretend like it's thinking
  variants:                  # chess variants to accept (http://lichess.org/variant)
    - standard
#   - fromPosition
    - antichess
    - atomic
    - chess960
    - crazyhouse
    - horde
    - kingOfTheHill
    - racingKings
    - threeCheck
  time_controls:             # time controls to accept
    - bullet
    - blitz
    - rapid
    - classical
    - correspondence
  modes:                     # game modes to accept
    - casual                 # unrated games
   #- rated                  # rated games - must comment if the engine doesn't try to win

